from os import getenv
from dotenv import load_dotenv

load_dotenv()

BOT_TOKEN = getenv("BOT_TOKEN")

WEBHOOK_URL = getenv("WEBHOOK_URL")
WEBHOOK_SECRET = getenv("WEBHOOK_SECRET")

MONGO_URI = getenv("MONGO_URI")
ADMIN_CHAT_ID = int(getenv("ADMIN_CHAT_ID"))
CHAT_THREAD_FEEDBACK = int(getenv("CHAT_THREAD_FEEDBACK") or "0")

SPREADSHEET_ID = getenv("SPREADSHEET_ID")
GOOGLE_SERVICE_ACCOUNT_FILENAME = getenv("GOOGLE_SERVICE_ACCOUNT_FILENAME")

WORK_HOURS_START = getenv("WORK_HOURS_START", "09:00")
WORK_HOURS_END = getenv("WORK_HOURS_END", "17:00")
TIMEZONE_OFFSET = int(getenv("TIMEZONE_OFFSET", "3"))

AFTER_HOURS_PHONE = getenv("AFTER_HOURS_PHONE")
